import json
import re
import shutil
import subprocess
import sys
import threading
import unittest
import uuid
from unittest import mock
from pathlib import Path

import requests


TOOL_ROOT = Path(__file__).resolve().parents[1]
TMP_ROOT = TOOL_ROOT / ".tmp-test-artifacts"
FIXTURES_ROOT = TOOL_ROOT / "tests" / "fixtures"
if str(TOOL_ROOT) not in sys.path:
    sys.path.insert(0, str(TOOL_ROOT))

from chatbi_smart_query_log_extractor.__main__ import main
from chatbi_smart_query_log_extractor.extractor import extract_report
from chatbi_smart_query_log_extractor.html_report import render_html
from chatbi_smart_query_log_extractor.interactive_server import build_report_server


QUESTION = "近7天销售额是多少"
ALT_QUESTION = "近7天销售额是多少?"
FULL_LOG = """2026-04-02 19:00:01.665 [INFO] [123456789012345] sql_template_match hit query: 近7天销售额是多少
2026-04-02 19:00:01.700 [INFO] [123456789012345] knowledge retriever success retrieved docs: sales_doc, shop_doc
2026-04-02 19:00:01.710 [INFO] [123456789012345] rewrite question from [old] [new] 请查询近7天销售额
2026-04-02 19:00:01.720 [INFO] [123456789012345] Schema链接完成
2026-04-02 19:00:01.730 [INFO] [123456789012345] 召回表: sales_order, shop_dim
2026-04-02 19:00:01.740 [INFO] [123456789012345] 表定义的IR：table sales_order(id, amount)
table shop_dim(shop_id, shop_name)
2026-04-02 19:00:01.760 [INFO] [123456789012345] code guardrail check result safe
2026-04-02 19:00:01.770 [INFO] [123456789012345] 生成器任务：{'messages': [{'role': 'system', 'content': '你是助手\\n请生成IR'}, {'role': 'user', 'content': '问题：近7天销售额\\n请输出\\'IR\\''}]}
2026-04-02 19:00:01.771 [DEBUG] [123456789012345] 生成器任务 fallback without colon
2026-04-02 19:00:01.780 [INFO] [123456789012345] 最终的IR
generated by llm
@dataclass
class FinalIR:
    metric: str
SELECT amount FROM sales_order
tables = get_tables_columns(table_exprs)
2026-04-02 19:05:01.665 [INFO] [223456789012345] sql_template_match hit query: 近7天销售额是多少
2026-04-02 19:05:01.710 [INFO] [223456789012345] rewrite question from [old] [new] 帮我查询近7天销售额
2026-04-02 19:05:01.770 [INFO] [223456789012345] 生成器任务：{"messages": [{"role": "system", "content": "系统提示\\n第二次"}, {"role": "user", "content": "用户问题\\n第二次"}]}
2026-04-02 19:05:01.780 [INFO] [223456789012345] 最终的IR
@dataclass
class SecondIR:
    ds_filter: str
SELECT amount FROM sales_order WHERE ds >= current_date - 7
tables = get_tables_columns(table_exprs)
"""

PARTIAL_LOG = """2026-04-02 20:00:01.665 [INFO] [323456789012345] sql_template_match hit query: 近7天销售额是多少
2026-04-02 20:00:01.770 [INFO] [323456789012345] 生成器任务：not-a-json-payload
2026-04-02 20:00:01.780 [INFO] [323456789012345] 最终的IR
@dataclass
class BrokenIR:
SELECT broken FROM data
"""

LIST_PROMPT_LOG = """2026-04-02 21:00:01.665 [INFO] [423456789012346] sql_template_match hit query: 近7天销售额是多少
2026-04-02 21:00:01.770 [INFO] [423456789012346] 生成器任务：[{'role': 'system', 'content': 'line 1\\nline 2 有个人叫\\'小明\\'\\n哈哈哈'}, {'role': 'user', 'content': 'line 3\\nline 4\\n'}]
2026-04-02 21:00:01.780 [INFO] [423456789012346] 最终的IR
@dataclass
class ListPromptIR:
tables = get_tables_columns(table_exprs)
"""


def _build_ir_only_report(complete_ir: str, request_id: str = "823456789012345") -> dict:
    return {
        "tool": "chatbi-smart-query-log-extractor",
        "version": "test",
        "source_log": "test.log",
        "generated_at": "2026-04-07T00:00:00",
        "total_questions": 1,
        "questions": [
            {
                "question": QUESTION,
                "total_matches": 1,
                "matches": [
                    {
                        "index": 1,
                        "request_id": request_id,
                        "anchor_timestamp": "2026-04-07 00:00:00.000",
                        "anchor_line": "anchor",
                        "line_number": 1,
                        "rag_results": [],
                        "rewritten_question": "",
                        "recalled_tables": [],
                        "ir_table_definition": "",
                        "final_prompt": {"raw": "", "system": "", "user": "", "combined": ""},
                        "generated_ir": "",
                        "complete_ir": complete_ir,
                        "missing_sections": [],
                        "parse_errors": [],
                    }
                ],
            }
        ],
    }


def _write_executor_config(
    config_path: Path,
    workspace: Path,
    python_bin: str | None = None,
    env: dict[str, str] | None = None,
) -> None:
    python_path = python_bin or sys.executable
    lines = [
        "default_executor: demo",
        "executors:",
        "  demo:",
        f"    project_root: {workspace.as_posix()}",
        f"    working_dir: {workspace.as_posix()}",
        f"    target_dir: {(workspace / 'generated').as_posix()}",
        f"    python_bin: {Path(python_path).as_posix()}",
        "    run_command:",
        "      - '{python_bin}'",
        "      - '{target_file}'",
        "    timeout_sec: 5",
        "    result_encoding: utf-8",
    ]
    if env:
        lines.append("    env:")
        for key, value in env.items():
            lines.append(f"      {key}: \"{value}\"")
    config_path.write_text("\n".join(lines), encoding="utf-8")


class ExtractorTests(unittest.TestCase):
    def test_extract_report_handles_complex_fixture_file(self) -> None:
        log_text = (FIXTURES_ROOT / "complex_chatbi.log").read_text(encoding="utf-8")

        report = extract_report(log_text, "complex_chatbi.log")

        self.assertEqual(report["total_questions"], 2)
        self.assertEqual(
            [question["question"] for question in report["questions"]],
            [QUESTION, ALT_QUESTION],
        )

        first_group = report["questions"][0]
        self.assertEqual(first_group["question"], QUESTION)
        self.assertEqual(first_group["total_matches"], 2)
        self.assertEqual(
            [match["request_id"] for match in first_group["matches"]],
            ["423456789012345", "523456789012345"],
        )

        first = first_group["matches"][0]
        self.assertEqual(len(first["rag_results"]), 2)
        self.assertEqual(first["rewritten_question"], "请帮我统计最近7天销售额")
        self.assertEqual(first["recalled_tables"], ["2026-04-03 09:15:00.050 [INFO] [423456789012345] Schema链接完成", "sales_order", "dim_calendar"])
        self.assertIn("join sales_order.ds = dim_calendar.ds", first["ir_table_definition"])
        self.assertNotIn("表定义的IR：", first["ir_table_definition"])
        self.assertIn("\n\n@dataclass", first["complete_ir"])
        self.assertNotIn("generated by llm", first["complete_ir"])
        self.assertEqual(first["parse_errors"], [])

        second = first_group["matches"][1]
        self.assertEqual(second["final_prompt"]["system"], "系统角色\n路径：\\\\server\\share\\prompt.txt")
        self.assertEqual(second["final_prompt"]["user"], '请输出"门店销售额" IR\n并保留 shop_id')
        self.assertIn("shop_id", second["generated_ir"])
        self.assertNotIn("最终的IR", second["generated_ir"])
        self.assertIn("@dataclass", second["generated_ir"])

        second_group = report["questions"][1]
        self.assertEqual(second_group["question"], ALT_QUESTION)
        self.assertEqual(second_group["total_matches"], 1)
        third = second_group["matches"][0]
        self.assertIn("rag_results", third["missing_sections"])
        self.assertIn("rewritten_question", third["missing_sections"])
        self.assertIn("final_prompt: failed to parse payload", "".join(third["parse_errors"]))
        self.assertIn("ir_table_definition: missing terminator", "".join(third["parse_errors"]))
        self.assertIn("generated_ir: missing terminator", "".join(third["parse_errors"]))
        self.assertIn("complete_ir", third["missing_sections"])

    def test_extract_report_collects_expected_sections_for_multiple_calls(self) -> None:
        report = extract_report(FULL_LOG, "sample.log", question_filter=QUESTION)

        self.assertEqual(report["total_questions"], 1)
        self.assertEqual(len(report["questions"]), 1)
        self.assertEqual(report["questions"][0]["question"], QUESTION)
        self.assertEqual(report["questions"][0]["total_matches"], 2)

        first = report["questions"][0]["matches"][0]
        self.assertEqual(first["request_id"], "123456789012345")
        self.assertEqual(first["anchor_timestamp"], "2026-04-02 19:00:01.665")
        self.assertIn("knowledge retriever success", first["rag_results"][0])
        self.assertEqual(first["rewritten_question"], "请查询近7天销售额")
        self.assertIn("sales_order, shop_dim", first["recalled_tables"])
        self.assertTrue(first["ir_table_definition"].startswith("table sales_order(id, amount)"))
        self.assertNotIn("表定义的IR", first["ir_table_definition"])
        self.assertNotIn("code guardrail check result", first["ir_table_definition"])
        self.assertEqual(first["final_prompt"]["system"], "你是助手\n请生成IR")
        self.assertEqual(first["final_prompt"]["user"], "问题：近7天销售额\n请输出'IR'")
        self.assertIn("你是助手\n请生成IR", first["final_prompt"]["combined"])
        self.assertTrue(first["generated_ir"].startswith("generated by llm"))
        self.assertIn("tables = get_tables_columns(table_exprs)", first["generated_ir"])
        self.assertNotIn("最终的IR", first["generated_ir"])
        self.assertNotIn("generated by llm", first["complete_ir"])
        self.assertIn("table shop_dim(shop_id, shop_name)\n\n@dataclass", first["complete_ir"])
        self.assertEqual(first["missing_sections"], [])
        self.assertEqual(first["parse_errors"], [])

        second = report["questions"][0]["matches"][1]
        self.assertEqual(second["request_id"], "223456789012345")
        self.assertEqual(second["anchor_timestamp"], "2026-04-02 19:05:01.665")
        self.assertIn("rag_results", second["missing_sections"])
        self.assertIn("ir_table_definition", second["missing_sections"])
        self.assertIn("complete_ir", second["missing_sections"])

    def test_extract_report_marks_partial_failures_and_preserves_prompt_raw_text(self) -> None:
        report = extract_report(PARTIAL_LOG, "partial.log")

        self.assertEqual(report["total_questions"], 1)
        self.assertEqual(report["questions"][0]["question"], QUESTION)
        match = report["questions"][0]["matches"][0]
        self.assertIn("rag_results", match["missing_sections"])
        self.assertIn("rewritten_question", match["missing_sections"])
        self.assertIn("final_prompt", "".join(match["parse_errors"]))
        self.assertEqual(match["final_prompt"]["raw"], "not-a-json-payload")
        self.assertIn("SELECT broken FROM data", match["generated_ir"])
        self.assertNotIn("最终的IR", match["generated_ir"])
        self.assertIn("generated_ir", "".join(match["parse_errors"]))
        self.assertIn("complete_ir", match["missing_sections"])

    def test_extract_report_parses_python_message_list_prompt(self) -> None:
        report = extract_report(LIST_PROMPT_LOG, "list-prompt.log")

        match = report["questions"][0]["matches"][0]
        self.assertEqual(match["final_prompt"]["system"], "line 1\nline 2 有个人叫'小明'\n哈哈哈")
        self.assertEqual(match["final_prompt"]["user"], "line 3\nline 4\n")
        self.assertEqual(
            match["final_prompt"]["combined"],
            "line 1\nline 2 有个人叫'小明'\n哈哈哈\n\nline 3\nline 4\n",
        )
        self.assertNotIn("final_prompt", "".join(match["parse_errors"]))

    def test_extract_report_returns_zero_questions_when_filter_not_found(self) -> None:
        report = extract_report(FULL_LOG, "sample.log", question_filter="不存在的问题")

        self.assertEqual(report["total_questions"], 0)
        self.assertEqual(report["questions"], [])

    def test_render_html_shows_navigation_prompt_and_missing_markers(self) -> None:
        report = extract_report((FIXTURES_ROOT / "complex_chatbi.log").read_text(encoding="utf-8"), "complex_chatbi.log")
        html = render_html(report)

        self.assertIn("近7天销售额是多少", html)
        self.assertIn("近7天销售额是多少?", html)
        self.assertIn("423456789012345", html)
        self.assertIn('href="#question-1"', html)
        self.assertIn('href="#question-2"', html)
        self.assertIn("<summary>RAG 检索结果</summary>", html)
        self.assertIn("<summary>IR 表定义</summary>", html)
        self.assertIn("<summary>最终 Prompt</summary>", html)
        self.assertIn("<summary>生成 IR 结果</summary>", html)
        self.assertNotIn("Prompt / system", html)
        self.assertNotIn("Prompt / user", html)
        self.assertNotIn("Prompt / combined", html)
        self.assertIn('data-execute-request-id="423456789012345"', html)
        self.assertIn('data-execute-output="final-prompt-question-1-match-1-result"', html)
        self.assertIn("executePrompt(this)", html)
        self.assertIn('class="copy-btn"', html)
        self.assertIn('title="复制 JSON"', html)
        self.assertIn('class="copy-feedback"', html)
        self.assertIn('aria-live="polite"', html)
        self.assertIn("已复制", html)
        self.assertIn('data-copy-target="final-prompt-question-1-match-1"', html)
        self.assertIn('data-copy-target="final-prompt-question-1-match-1-messages-json"', html)
        self.assertIn('id="final-prompt-question-1-match-1-messages-json"', html)
        self.assertIn('&quot;messages&quot;:', html)
        self.assertIn('&quot;role&quot;: &quot;system&quot;', html)
        self.assertIn('&quot;role&quot;: &quot;user&quot;', html)
        self.assertIn('data-copy-target="complete-ir-question-1-match-1"', html)
        self.assertIn('id="complete-ir-question-1-match-1-filename"', html)
        self.assertIn('placeholder="case_时间戳.py"', html)
        self.assertIn('class="execute-btn"', html)
        self.assertIn('data-execute-request-id="423456789012345"', html)
        self.assertIn('data-execute-output="complete-ir-question-1-match-1-result"', html)
        self.assertIn('data-execute-filename-input="complete-ir-question-1-match-1-filename"', html)
        self.assertIn(">▶</button>", html)
        self.assertIn("executeIR(this)", html)
        self.assertIn("feedback.classList.add('visible')", html)
        self.assertIn("copySection(this)", html)
        self.assertNotIn('<details class="section collapsible" open>', html)
        self.assertIn("完整 IR", html)
        self.assertIn("未命中该字段", html)

    def test_execute_prompt_endpoint_uses_original_two_message_payload(self) -> None:
        report = extract_report(FULL_LOG, "sample.log", question_filter=QUESTION)
        server = build_report_server(report, render_html(report), host="127.0.0.1", port=0)
        thread = threading.Thread(target=server.serve_forever, daemon=True)
        thread.start()
        try:
            response = requests.post(
                f"{server.base_url}/api/execute-prompt",
                json={"request_id": "123456789012345"},
                timeout=5,
            )

            self.assertEqual(response.status_code, 200)
            payload = response.json()
            self.assertEqual(payload["object"], "chat.completion")
            content = payload["choices"][0]["message"]["content"]
            self.assertIn("FAKE RESPONSE", content)
            self.assertIn("你是助手", content)
            self.assertIn("问题：近7天销售额", content)
            self.assertNotIn("生成器任务", content)
        finally:
            server.shutdown()
            server.server_close()
            thread.join(timeout=5)

    def test_service_page_supports_file_and_directory_selection(self) -> None:
        server = build_report_server(None, None, host="127.0.0.1", port=0)
        thread = threading.Thread(target=server.serve_forever, daemon=True)
        thread.start()
        try:
            response = requests.get(f"{server.base_url}/", timeout=5)
            self.assertEqual(response.status_code, 200)
            html = response.text
            self.assertIn('id="log-file-input"', html)
            self.assertIn('id="log-directory-input"', html)
            self.assertIn("webkitdirectory", html)
            self.assertIn('id="selected-files"', html)
            self.assertIn('id="report-frame"', html)
            self.assertIn("/api/report", html)
        finally:
            server.shutdown()
            server.server_close()
            thread.join(timeout=5)

    def test_report_upload_endpoint_parses_selected_log_and_updates_current_report(self) -> None:
        server = build_report_server(None, None, host="127.0.0.1", port=0)
        thread = threading.Thread(target=server.serve_forever, daemon=True)
        thread.start()
        try:
            payload = {
                "source_name": "uploaded.log",
                "content_base64": __import__("base64").b64encode(FULL_LOG.encode("utf-8")).decode("ascii"),
            }
            parse_response = requests.post(f"{server.base_url}/api/report", json=payload, timeout=5)
            self.assertEqual(parse_response.status_code, 200)
            parse_payload = parse_response.json()
            self.assertEqual(parse_payload["source_log"], "uploaded.log")
            self.assertEqual(parse_payload["total_questions"], 1)
            self.assertIn("/report/current", parse_payload["report_url"])

            report_response = requests.get(f"{server.base_url}/report/current", timeout=5)
            self.assertEqual(report_response.status_code, 200)
            self.assertIn("近7天销售额是多少", report_response.text)

            execute_response = requests.post(
                f"{server.base_url}/api/execute-prompt",
                json={"request_id": "123456789012345"},
                timeout=5,
            )
            self.assertEqual(execute_response.status_code, 200)
            self.assertIn("FAKE RESPONSE", execute_response.json()["choices"][0]["message"]["content"])
        finally:
            server.shutdown()
            server.server_close()
            thread.join(timeout=5)

    def test_execute_ir_endpoint_writes_enhanced_source_and_returns_stdout(self) -> None:
        TMP_ROOT.mkdir(exist_ok=True)
        temp_dir = TMP_ROOT / f"ir-run-{uuid.uuid4().hex}"
        temp_dir.mkdir(parents=True, exist_ok=False)
        try:
            config_path = temp_dir / "executors.local.yaml"
            _write_executor_config(config_path, temp_dir)
            report = _build_ir_only_report(
                "\n".join(
                    [
                        "def to_sql(intent_result):",
                        "    return f'SQL::{intent_result}'",
                        "",
                        "intent_result = 'ok'",
                        "resulted_sql = to_sql(intent_result)",
                    ]
                ),
                request_id="823456789012345",
            )
            server = build_report_server(
                report,
                "html",
                host="127.0.0.1",
                port=0,
                config_path=config_path,
            )
            thread = threading.Thread(target=server.serve_forever, daemon=True)
            thread.start()
            try:
                response = requests.post(
                    f"{server.base_url}/api/execute-ir",
                    json={"request_id": "823456789012345", "source_filename": "demo_case"},
                    timeout=5,
                )
                self.assertEqual(response.status_code, 200)
                payload = response.json()
                self.assertTrue(payload["success"])
                self.assertEqual(payload["exit_code"], 0)
                self.assertEqual(payload["executor"], "demo")
                self.assertIn("SQL::ok", payload["stdout"])
                self.assertEqual(payload["stderr"], "")
                self.assertTrue(payload["target_file"].endswith("demo_case.py"))
                target_path = Path(payload["target_file"])
                self.assertTrue(target_path.is_file())
                enhanced = target_path.read_text(encoding="utf-8")
                self.assertIn("resulted_sql = to_sql(intent_result)\nprint(resulted_sql)", enhanced)
            finally:
                server.shutdown()
                server.server_close()
                thread.join(timeout=5)
        finally:
            shutil.rmtree(temp_dir, ignore_errors=True)

    def test_execute_ir_endpoint_can_import_project_modules_like_pycharm(self) -> None:
        TMP_ROOT.mkdir(exist_ok=True)
        temp_dir = TMP_ROOT / f"ir-import-run-{uuid.uuid4().hex}"
        temp_dir.mkdir(parents=True, exist_ok=False)
        try:
            src_dir = temp_dir / "src"
            src_dir.mkdir()
            (src_dir / "__init__.py").write_text("", encoding="utf-8")
            (src_dir / "helpers.py").write_text(
                "\n".join(
                    [
                        "def build_sql(intent_result):",
                        "    return f'SQL::{intent_result}::from-src'",
                    ]
                ),
                encoding="utf-8",
            )
            config_path = temp_dir / "executors.local.yaml"
            _write_executor_config(config_path, temp_dir)
            report = _build_ir_only_report(
                "\n".join(
                    [
                        "from src.helpers import build_sql",
                        "",
                        "def to_sql(intent_result):",
                        "    return build_sql(intent_result)",
                        "",
                        "intent_result = 'ok'",
                        "resulted_sql = to_sql(intent_result)",
                    ]
                ),
                request_id="833456789012345",
            )
            server = build_report_server(report, "html", host="127.0.0.1", port=0, config_path=config_path)
            thread = threading.Thread(target=server.serve_forever, daemon=True)
            thread.start()
            try:
                response = requests.post(
                    f"{server.base_url}/api/execute-ir",
                    json={"request_id": "833456789012345", "source_filename": "import_case"},
                    timeout=5,
                )
                self.assertEqual(response.status_code, 200)
                payload = response.json()
                self.assertTrue(payload["success"])
                self.assertEqual(payload["exit_code"], 0)
                self.assertIn("SQL::ok::from-src", payload["stdout"])
            finally:
                server.shutdown()
                server.server_close()
                thread.join(timeout=5)
        finally:
            shutil.rmtree(temp_dir, ignore_errors=True)

    def test_execute_ir_endpoint_applies_custom_environment_variables(self) -> None:
        TMP_ROOT.mkdir(exist_ok=True)
        temp_dir = TMP_ROOT / f"ir-env-run-{uuid.uuid4().hex}"
        temp_dir.mkdir(parents=True, exist_ok=False)
        try:
            config_path = temp_dir / "executors.local.yaml"
            _write_executor_config(
                config_path,
                temp_dir,
                env={"IR_EXTRA_FLAG": "prefix::{project_root}"},
            )
            report = _build_ir_only_report(
                "\n".join(
                    [
                        "import os",
                        "",
                        "def to_sql(intent_result):",
                        "    return os.environ['IR_EXTRA_FLAG']",
                        "",
                        "intent_result = 'ok'",
                        "resulted_sql = to_sql(intent_result)",
                    ]
                ),
                request_id="843456789012345",
            )
            server = build_report_server(report, "html", host="127.0.0.1", port=0, config_path=config_path)
            thread = threading.Thread(target=server.serve_forever, daemon=True)
            thread.start()
            try:
                response = requests.post(
                    f"{server.base_url}/api/execute-ir",
                    json={"request_id": "843456789012345", "source_filename": "env_case"},
                    timeout=5,
                )
                self.assertEqual(response.status_code, 200)
                payload = response.json()
                self.assertTrue(payload["success"])
                self.assertIn(f"prefix::{temp_dir}", payload["stdout"])
            finally:
                server.shutdown()
                server.server_close()
                thread.join(timeout=5)
        finally:
            shutil.rmtree(temp_dir, ignore_errors=True)

    def test_execute_ir_endpoint_generates_default_case_filename(self) -> None:
        TMP_ROOT.mkdir(exist_ok=True)
        temp_dir = TMP_ROOT / f"default-ir-run-{uuid.uuid4().hex}"
        temp_dir.mkdir(parents=True, exist_ok=False)
        try:
            config_path = temp_dir / "executors.local.yaml"
            _write_executor_config(config_path, temp_dir)
            report = _build_ir_only_report(
                "\n".join(
                    [
                        "def to_sql(intent_result):",
                        "    return intent_result",
                        "",
                        "intent_result = 'ok'",
                        "resulted_sql = to_sql(intent_result)",
                    ]
                ),
                request_id="923456789012345",
            )
            server = build_report_server(report, "html", host="127.0.0.1", port=0, config_path=config_path)
            thread = threading.Thread(target=server.serve_forever, daemon=True)
            thread.start()
            try:
                response = requests.post(
                    f"{server.base_url}/api/execute-ir",
                    json={"request_id": "923456789012345"},
                    timeout=5,
                )
                self.assertEqual(response.status_code, 200)
                payload = response.json()
                self.assertRegex(Path(payload["target_file"]).name, r"^case_\d{17}\.py$")
            finally:
                server.shutdown()
                server.server_close()
                thread.join(timeout=5)
        finally:
            shutil.rmtree(temp_dir, ignore_errors=True)

    def test_execute_ir_endpoint_rejects_invalid_filename(self) -> None:
        TMP_ROOT.mkdir(exist_ok=True)
        temp_dir = TMP_ROOT / f"bad-name-ir-run-{uuid.uuid4().hex}"
        temp_dir.mkdir(parents=True, exist_ok=False)
        try:
            config_path = temp_dir / "executors.local.yaml"
            _write_executor_config(config_path, temp_dir)
            report = _build_ir_only_report("resulted_sql = to_sql(intent_result)")
            server = build_report_server(report, "html", host="127.0.0.1", port=0, config_path=config_path)
            thread = threading.Thread(target=server.serve_forever, daemon=True)
            thread.start()
            try:
                response = requests.post(
                    f"{server.base_url}/api/execute-ir",
                    json={"request_id": "823456789012345", "source_filename": "..\\bad.py"},
                    timeout=5,
                )
                self.assertEqual(response.status_code, 400)
                self.assertIn("source_filename", response.json()["error"])
            finally:
                server.shutdown()
                server.server_close()
                thread.join(timeout=5)
        finally:
            shutil.rmtree(temp_dir, ignore_errors=True)

    def test_execute_ir_endpoint_reports_missing_config(self) -> None:
        report = _build_ir_only_report("resulted_sql = to_sql(intent_result)")
        server = build_report_server(
            report,
            "html",
            host="127.0.0.1",
            port=0,
            config_path=TMP_ROOT / "missing-executors.local.yaml",
        )
        thread = threading.Thread(target=server.serve_forever, daemon=True)
        thread.start()
        try:
            response = requests.post(
                f"{server.base_url}/api/execute-ir",
                json={"request_id": "823456789012345"},
                timeout=5,
            )
            self.assertEqual(response.status_code, 500)
            self.assertIn("executors.local.yaml", response.json()["error"])
        finally:
            server.shutdown()
            server.server_close()
            thread.join(timeout=5)

    def test_execute_ir_endpoint_rejects_missing_sql_anchor(self) -> None:
        TMP_ROOT.mkdir(exist_ok=True)
        temp_dir = TMP_ROOT / f"missing-anchor-ir-run-{uuid.uuid4().hex}"
        temp_dir.mkdir(parents=True, exist_ok=False)
        try:
            config_path = temp_dir / "executors.local.yaml"
            _write_executor_config(config_path, temp_dir)
            report = _build_ir_only_report("print('no sql anchor')", request_id="723456789012345")
            server = build_report_server(report, "html", host="127.0.0.1", port=0, config_path=config_path)
            thread = threading.Thread(target=server.serve_forever, daemon=True)
            thread.start()
            try:
                response = requests.post(
                    f"{server.base_url}/api/execute-ir",
                    json={"request_id": "723456789012345"},
                    timeout=5,
                )
                self.assertEqual(response.status_code, 400)
                self.assertIn("resulted_sql = to_sql(intent_result)", response.json()["error"])
            finally:
                server.shutdown()
                server.server_close()
                thread.join(timeout=5)
        finally:
            shutil.rmtree(temp_dir, ignore_errors=True)


class CliTests(unittest.TestCase):
    @mock.patch("chatbi_smart_query_log_extractor.__main__.serve_report")
    def test_main_can_start_empty_service_without_log(self, mock_serve_report: mock.Mock) -> None:
        exit_code = main(["--serve"])
        self.assertEqual(exit_code, 0)
        mock_serve_report.assert_called_once()
        args, kwargs = mock_serve_report.call_args
        self.assertIsNone(args[0])
        self.assertEqual(args[1], "")
        self.assertEqual(kwargs["host"], "127.0.0.1")
        self.assertEqual(kwargs["port"], 8000)

    def test_main_returns_no_match_exit_code(self) -> None:
        TMP_ROOT.mkdir(exist_ok=True)
        temp_dir = TMP_ROOT / f"run-{uuid.uuid4().hex}"
        temp_dir.mkdir(parents=True, exist_ok=False)
        try:
            log_path = temp_dir / "empty.log"
            log_path.write_text(FULL_LOG, encoding="utf-8")

            exit_code = main(
                [
                    "--log",
                    str(log_path),
                    "--question",
                    "不存在的问题",
                    "--output-dir",
                    str(temp_dir),
                ]
            )

            self.assertEqual(exit_code, 3)
        finally:
            shutil.rmtree(temp_dir, ignore_errors=True)

    def test_cli_generates_html_and_json_with_gbk_fallback(self) -> None:
        TMP_ROOT.mkdir(exist_ok=True)
        temp_dir = TMP_ROOT / f"run-{uuid.uuid4().hex}"
        temp_dir.mkdir(parents=True, exist_ok=False)
        try:
            log_path = temp_dir / "gbk.log"
            output_dir = temp_dir / "out"
            output_dir.mkdir()
            log_path.write_bytes(FULL_LOG.encode("gbk"))

            completed = subprocess.run(
                [
                    sys.executable,
                    "-m",
                    "chatbi_smart_query_log_extractor",
                    "--log",
                    str(log_path),
                    "--output-dir",
                    str(output_dir),
                ],
                cwd=TOOL_ROOT,
                capture_output=True,
                text=True,
            )

            self.assertEqual(completed.returncode, 4)
            json_files = list(output_dir.glob("*.json"))
            html_files = list(output_dir.glob("*.html"))
            self.assertEqual(len(json_files), 1)
            self.assertEqual(len(html_files), 1)

            payload = json.loads(json_files[0].read_text(encoding="utf-8"))
            self.assertEqual(payload["total_questions"], 1)
            self.assertEqual(payload["questions"][0]["question"], QUESTION)
            self.assertEqual(payload["questions"][0]["matches"][0]["request_id"], "123456789012345")
        finally:
            shutil.rmtree(temp_dir, ignore_errors=True)


if __name__ == "__main__":
    unittest.main()
